### ISSUE TITLE
Sensor werkt niet meer

### ISSUE THREAD

**Issue by maxxie85** [pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer#4]
Krijg error meldingen in Hass dat er niet meer geupdate kan worden. Laatste versie via HACS geïnstalleerd v1.1.3 op Home-Assistant CORE 0.105.5

Melding in Hass:
`Update for sensor.afvalwijzer_oud_papier fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/groningen_afvalwijzer/sensor.py", line 201, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/groningen_afvalwijzer/sensor.py", line 136, in update
    if p.tables[0]:
IndexError: list index out of range`

**Comment by IcyPalm** [comment]
Deze melding verteld je dat de sensor geen data meer kan ophalen(data update) 

Dit heeft er meestal mee te maken dat de website van de gemeente Groningen het niet helemaal lekker doet. Iets wat regelmatig gebeurt. Morgen werkt hij waarschijnlijk al gewoon weer 👍 

Je kan altijd even met de hand checken of het werkt via: https://gemeente.groningen.nl/afvalwijzer/groningen/

En op dit moment(23 feb 2020, 21:15) doet de website het inderdaad niet en is de foutmelding logisch.

Mogelijk dat we in de code een check kunnen toevoegen die kan controleren of het aan de website zelf ligt
