### ISSUE TITLE
Foutmeldingen in de logs

### ISSUE THREAD

**Issue by hapklaar** [pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer#6]
In home-assistant.log zie ik constant deze error. In een eerder issue zag ik dat dit zou komen doordat de site van Gemeente Groningen niet bereikbaar zou zijn, maar daar kan ik gewoon bij en ook de datum, uitlezen. Is er misschien iets anders aan de hand?

`2021-01-13 22:43:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalwijzer_oud_papier fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/groningen_afvalwijzer/sensor.py", line 201, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/groningen_afvalwijzer/sensor.py", line 136, in update
    if p.tables[0]:
IndexError: list index out of range`

**Comment by IcyPalm** [comment]
Ik zie hetzelfde in mijn logs, in ieder geval sinds 11 januari zijn er problemen.
Kan er vanavond mogelijk wel even naar kijken

**Comment by pippyn** [comment]
Could you share your config (with your address) with me? Maybe [DM me on HA community forum](https://community.home-assistant.io/u/pippyn/) to keep your address private.

**Comment by IcyPalm** [comment]
I was just checking the website of the Gemeente Groningen(https://gemeente.groningen.nl/afval/afvalwijzer)
and I noticed that they now link to https://www.mijnafvalwijzer.nl/ and not use their own implementation it seems

**Comment by pippyn** [comment]
Then I would recommend you use my [other sensor](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/). Which has support for mijnafvalwijzer.nl (and a lot more options and features).
